//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аптека
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicineSet()
        {
            this.AvailabilitySet = new HashSet<AvailabilitySet>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ReleaseForm { get; set; }
        public string Dosage { get; set; }
        public string Manufacturer { get; set; }
        public string ShelfLife { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailabilitySet> AvailabilitySet { get; set; }
    }
}
